export const ADD_CASES = "ADD_CASES";
export const SUBTRACT_CASES = "SUBTRACT_CASES";
export const INCREASE_ID_COVID_DATA = "INCREASE_ID_COVID_DATA";

export const CHANGE_USER_CENTER_T = "CHANGE_USER_CENTER_T";
export const CHANGE_USER_CENTER_F = "CHANGE_USER_CENTER_F";
export const ADD_USER_COVID_REPORT = "ADD_USER_COVID_REPORT";
export const SUBTRACT_USER_COVID_REPORT = "SUBTRACT_USER_COVID_REPORT";