export const ADD_CASES = 'ADD_CASES';
export const SUBTRACT_CASES = 'SUBTRACT_CASES';

export const CHANGE_USER_CENTER_T= 'CHANGE_USER_CENTER_T';
export const CHANGE_USER_CENTER_F = 'CHANGE_USER_CENTER_F';