export const ADD_CASES = "ADD_CASES";
export const SUBTRACT_CASES = "SUBTRACT_CASES";
export const API_COVID_CASES = "API_COVID_CASES";

export const INCREASE_ID_COVID_DATA = "INCREASE_ID_COVID_DATA";

export const COVID_COUNT_WITHIN_RADIUS = "COVID_COUNT_WITHIN_RADIUS";

export const CHANGE_USER_CENTER_T = "CHANGE_USER_CENTER_T";
export const CHANGE_USER_CENTER_F = "CHANGE_USER_CENTER_F";

export const ADD_COVID_MODE_T = "ADD_COVID_MODE_T";
export const ADD_COVID_MODE_F = "ADD_COVID_MODE_F";

export const SUBTRACT_COVID_MODE_T = "SUBTRACT_COVID_MODE_T";
export const SUBTRACT_COVID_MODE_F = "SUBTRACT_COVID_MODE_F";

export const ADD_USER_COVID_REPORT = "ADD_USER_COVID_REPORT";
export const SUBTRACT_USER_COVID_REPORT = "SUBTRACT_USER_COVID_REPORT";
